CREATE DATABASE QUANLIKHACHSAN GO
USE QUANLIKHACHSAN 
GO

------------- CREATE TABLE -----------------
--KHACHHANG
CREATE TABLE KHACHHANG
(
	MaKH VARCHAR(5) NOT NULL PRIMARY KEY,
	GioiTinh NVARCHAR(3) NOT NULL,
	TenKH NVARCHAR(50) NOT NULL,
	Cmnd INT NOT NULL,
	DiaChi NVARCHAR(50) NOT NULL,
	QuocTich NVARCHAR(50) NOT NULL,
	Sdt INT NOT NULL,
	Email NVARCHAR(50) NOT NULL
)
ALTER TABLE KHACHHANG ADD NamSinh DATE
--NHANVIEN
CREATE TABLE NHANVIEN
(
	MaNV VARCHAR(5) NOT NULL PRIMARY KEY,
	TenNV NVARCHAR(50) NOT NULL,
	GioiTinh NVARCHAR(3) NOT NULL,
	NamSinh DATE NOT NULL,
	Cmnd INT NOT NULL,
	Sdt INT NOT NULL, 
	Email NVARCHAR(50) NOT NULL,
)
--PHIEU_DANGKI
CREATE TABLE PHIEU_DANGKI
(
	MaPDK VARCHAR(5) NOT NULL PRIMARY KEY,
	NgayDen DATE NOT NULL,
	NgayDi DATE,
	SoPhong INT NOT NULL,
	TraTruoc FLOAT,
	MaKH VARCHAR(5) NOT NULL
)
ALTER TABLE PHIEU_DANGKI ADD MaNV VARCHAR(5)
--DANGKI_DICHVU
CREATE TABLE DANGKI_DICHVU
(
	MaDV VARCHAR(5) NOT NULL,
	MaPDK VARCHAR(5) NOT NULL
)
--DANGKI_PHONG
CREATE TABLE DANGKI_PHONG
(
	MaP VARCHAR(5) NOT NULL,
	MaPDK VARCHAR(5) NOT NULL
)
--PHIEU_THANHTOAN
CREATE TABLE PHIEU_THANHTOAN
(
	MaPTT VARCHAR(5) NOT NULL PRIMARY KEY,
	SoNgay INT NOT NULL,
	NgayThanhToan DATE NOT NULL,
	TongTien FLOAT,
	VAT FLOAT,
	TienPhaiTra FLOAT,
	MaPDK VARCHAR(5) NOT NULL
)
ALTER TABLE PHIEU_THANHTOAN ADD MaNV VARCHAR(5)
--DICHVU
CREATE TABLE DICHVU
(
	MaDV VARCHAR(5) NOT NULL PRIMARY KEY,
	TenDV NVARCHAR(50) NOT NULL,
	GiaDV FLOAT NOT NULL
)
--PHONG
CREATE TABLE PHONG
(
	MaP VARCHAR(5) NOT NULL PRIMARY KEY,
	TenP NVARCHAR(50) NOT NULL,
	TrangThai NVARCHAR(5) NOT NULL
)
--HOADON
CREATE TABLE HOADON
(	
	MaHD VARCHAR(5) NOT NULL PRIMARY KEY,
	TenKhaiThue NVARCHAR(50) NOT NULL,
	MaSoThue NVARCHAR(10) NOT NULL,
	MAPTT VARCHAR(5) NOT NULL
)
--KIEU_PHONG
CREATE TABLE KIEU_PHONG
(
	MaKP VARCHAR(5) NOT NULL PRIMARY KEY,
	TenKP NVARCHAR(50) NOT NULL
)
ALTER TABLE KIEU_PHONG ADD TrangBi NVARCHAR(100)

--GIA_PHONG
CREATE TABLE GIA_PHONG
(
	Gia FLOAT NOT NULL,
	MaP VARCHAR(5) NOT NULL,
	MaKP VARCHAR(5) NOT NULL,
	MaLP VARCHAR(5) NOT NULL
)
--LOAI_PHONG
CREATE TABLE LOAI_PHONG
(
	MaLP VARCHAR(5) NOT NULL PRIMARY KEY,
	TenLP NVARCHAR(50) NOT NULL,
	TrangBi NVARCHAR(50) NOT NULL
)
ALTER TABLE LOAI_PHONG
DROP COLUMN TrangBi;
ALTER TABLE LOAI_PHONG ADD MoTa NVARCHAR(100)
--THONGTIN_KHACHSAN
CREATE TABLE THONGTIN_KHACHSAN
(
	TenKS NVARCHAR(50) NOT NULL,
	DiaChi NVARCHAR(50) NOT NULL,
	Sdt INT NOT NULL,
	Email NVARCHAR(50) NOT NULL
)

----------------- CONSTRAINT --------------------
--KHACHHANG
--PHIEU_DANGKI
ALTER TABLE PHIEU_DANGKI ADD CONSTRAINT FK_PHIEUDANGKI_KHACHHANG FOREIGN KEY(MaKH) REFERENCES KHACHHANG(MaKH)
ALTER TABLE PHIEU_DANGKI ADD CONSTRAINT FK_PHIEUDANGKI_NHANVIEN FOREIGN KEY(MaNV) REFERENCES NHANVIEN(MaNV)
--DANGKI_DICHVU
ALTER TABLE DANGKI_DICHVU ADD CONSTRAINT FK_DANGKIDICHVU_PHIEUDANGKI FOREIGN KEY(MaPDK) REFERENCES PHIEU_DANGKI(MaPDK)
ALTER TABLE DANGKI_DICHVU ADD CONSTRAINT FK_DANGKIDICHVU_DICHVU FOREIGN KEY(MaDV) REFERENCES DICHVU(MaDV)
--DANGKI_PHONG
ALTER TABLE DANGKI_PHONG ADD CONSTRAINT FK_DANGKIPHONG_PHIEUDANGKI FOREIGN KEY(MaPDK) REFERENCES PHIEU_DANGKI(MaPDK)
ALTER TABLE DANGKI_PHONG ADD CONSTRAINT FK_DANGKIPHONG_PHONG FOREIGN KEY(MaP) REFERENCES PHONG(MaP)
--PHIEU_THANHTOAN
ALTER TABLE PHIEU_THANHTOAN ADD CONSTRAINT FK_PHIEUTHANHTOAN_PHIEUDANGKI FOREIGN KEY(MaPDK) REFERENCES PHIEU_DANGKI(MaPDK)
ALTER TABLE PHIEU_THANHTOAN ADD CONSTRAINT FK_PHIEUTHANHTOAN_NHANVIEN FOREIGN KEY(MaNV) REFERENCES NHANVIEN(MaNV)
--DICHVU
--PHONG
ALTER TABLE PHONG ADD CONSTRAINT FK_PHONG_KIEUPHONG FOREIGN KEY(MaKP) REFERENCES KIEUPHONG(MaKP)
ALTER TABLE PHONG ADD CONSTRAINT FK_PHONG_LOAIPHONG FOREIGN KEY(MaLP) REFERENCES LOAIPHONG(MaLP)
--HOADON
ALTER TABLE HOADON ADD CONSTRAINT FK_HOADON_PHIEUTHANHTOAN FOREIGN KEY(MaPTT) REFERENCES PHIEU_THANHTOAN(MaPTT)
--KIEU_PHONG
--GIA_PHONG
ALTER TABLE GIA_PHONG ADD CONSTRAINT FK_GIAPHONG_PHONG FOREIGN KEY(MaP) REFERENCES PHONG(MaP)
ALTER TABLE GIA_PHONG ADD CONSTRAINT FK_GIAPHONG_KIEUPHONG FOREIGN KEY(MaKP) REFERENCES KIEU_PHONG(MaKP)
ALTER TABLE GIA_PHONG ADD CONSTRAINT FK_GIAPHONG_LOAIPHONG FOREIGN KEY(MaLP) REFERENCES LOAI_PHONG(MaLP)
--LOAI_PHONG
--THONGTIN_KHACHSAN
alter table PHIEU_DANGKI drop constraint FK_PHIEUDANGKI_KHACHHANG